site_name: Robin's Apoli Additions

nav:
  - Home: index.md
  - Types:
    - Task Types: task_types.md
    - Power Types: power_types.md
    - Data Types: data_types.md
  - Action Types:
    - Entity Action Types: entity_action_types.md
    - Bientity Action Types: bientity_action_types.md
    - Block Action Types: block_action_types.md
    - Item Action Types: item_action_types.md
  - Condition Types:
    - Entity Condition Types: entity_condition_types.md
    - Bientity Condition Types: bientity_condition_types.md
    - Block Condition Types: block_condition_types.md
    - Item Condition Types: item_condition_types.md
  - JSON:
    - Action JSON: action_json.md
    - Condition JSON: condition_json.md
    - Choice JSON: choice_json.md
    - Choice Layer JSON: choice_layer_json.md
    - Keybinding JSON: keybinding_json.md
  - Other:
    - Tag Extensions: tag_extensions.md
    - Origin Selectors: origin_selectors.md

theme:
    name: material
    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: deep purple
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: deep purple
          toggle:
            icon: material/toggle-switch
            name: Switch to dark mode

separator: '_'
plugins:
    - search
    - mermaid2:
        version: 8.6.4
        arguments:
            theme: 'neutral'

markdown_extensions:
    - admonition
extra_javascript:
    - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js